# Generated by Django 3.2.13 on 2022-11-18 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_title', models.CharField(max_length=200, verbose_name='Position Title')),
                ('type', models.CharField(max_length=200, verbose_name='Type')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('des_skills', models.TextField(verbose_name='Desired Skills')),
                ('description', models.TextField(verbose_name='Description')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('exp_date', models.DateField(verbose_name='Expiration Date')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruiter.recruiterprofile')),
            ],
        ),
    ]
