# Generated by Django 3.2.13 on 2022-11-19 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_auto_20221118_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='interested_candidates',
            field=models.PositiveIntegerField(default=0, verbose_name='Interested Candidates'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterprofile'),
        ),
    ]
