# Generated by Django 4.1.2 on 2022-12-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_auto_20221119_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='interested_ids',
            field=models.TextField(default='', verbose_name='Interested IDs'),
        ),
    ]
