# Generated by Django 4.1.2 on 2022-12-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidateprofile_uninterested_ids'),
        ('recruiter', '0004_jobpost_interested_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_salary', models.PositiveIntegerField(default=0, verbose_name='Yearly Salary')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('accepted', models.IntegerField(default=0, verbose_name='Accepted')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobpost')),
            ],
        ),
    ]
