# Generated by Django 3.2.13 on 2022-11-14 21:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('zip_code', models.IntegerField(validators=[django.core.validators.MinLengthValidator(5, 'Zip Code must be 5 digits.'), django.core.validators.MaxLengthValidator(5, 'Zip Code must be 5 digits.')], verbose_name='Zip Code')),
                ('bio', models.CharField(max_length=500, verbose_name='Profile Bio')),
                ('skills', models.TextField(verbose_name='Skills')),
                ('github', models.CharField(max_length=200, verbose_name='Github Username')),
                ('experience', models.PositiveSmallIntegerField(verbose_name='Years Of Experience')),
                ('education', models.TextField(verbose_name='Education')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
