# Generated by Django 4.1.2 on 2022-12-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.IntegerField(verbose_name='Years Of Experience'),
        ),
    ]
