# Generated by Django 4.1.2 on 2022-12-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidateprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='uninterested_ids',
            field=models.TextField(default='', verbose_name='Uninterested IDs'),
        ),
    ]
