# Generated by Django 4.1.3 on 2022-12-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0003_candidateprofile_uninterested_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="compatability_score",
            field=models.FloatField(default=0, verbose_name="Compatability Score"),
        ),
    ]
